name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
    - name: Install and Setup tmate
      run: |
        brew install tmate
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        SSH_INFO=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        WEB_INFO=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
        echo "SSH access: $SSH_INFO"
        echo "Web-based terminal: $WEB_INFO"
          
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
