name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Anydesk
        run: |
          curl -o Anydesk.dmg https://download.anydesk.com/anydesk.dmg
          hdiutil attach Anydesk.dmg
          sudo cp -R /Volumes/AnyDesk/AnyDesk.app /Applications
          hdiutil detach /Volumes/AnyDesk

      - name: Set up unattended access
        run: |
          echo -n "password_hash" > ~/Library/Application\ Support/AnyDesk/service.conf
          echo -n "YourStrongPassword" >> ~/Library/Application\ Support/AnyDesk/service.conf

      - name: MacOS System running...
        uses: mxschmitt/action-tmate@v2
