name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
    - name: Install tmate
      run: |
        brew install tmate || echo "tmate is already installed"

    - name: Display tmate session information
      run: |
        if tmate -S /tmp/tmate.sock has-session 2>/dev/null; then
          echo "Using existing tmate session."
        else
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
        fi
        SSH_INFO=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        WEB_INFO=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
        echo "SSH access: $SSH_INFO"
        echo "Web-based terminal: $WEB_INFO"

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
