name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
    - name: Install RustDesk
      run: |
        # Download RustDesk
        curl -L -o rustdesk.dmg "https://github.com/rustdesk/rustdesk/releases/latest/download/RustDesk-darwin-x64.dmg"

        # Mount the DMG
        hdiutil attach rustdesk.dmg -nobrowse -quiet
        sudo cp -R /Volumes/RustDesk/RustDesk.app /Applications/
        hdiutil detach /Volumes/RustDesk -quiet

    - name: Setup RustDesk
      run: |
        # Start RustDesk in background
        open -a RustDesk

        # Wait for RustDesk to initialize
        sleep 30  # Adjust the sleep duration if necessary

    - name: Retrieve RustDesk ID
      run: |
        # Use AppleScript to get RustDesk ID
        rustDeskID=$(osascript <<EOF
        tell application "RustDesk"
          activate
          delay 10  # Adjust the delay as needed
          -- Insert code here to interact with RustDesk and retrieve the ID
          set rustDeskID to (do shell script "ps aux | grep RustDesk | grep -v grep | awk '{print $2}'")
          return rustDeskID
        end tell
        EOF
        )
        echo "RustDesk ID: $rustDeskID"
        echo "$rustDeskID" > rustdesk_id.txt

    - name: Send RustDesk ID to Webhook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        rustDeskID=$(cat rustdesk_id.txt)
        curl -X POST $WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d '{"rustDeskID": "'"$rustDeskID"'"}'

    - name: Keep MacOS Runner Active
      run: sleep 3600  # Keeps the runner active for 1 hour; adjust as needed
